name: deploy

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:


jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 85.142.89.188
          port: 22
          username: ilya
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd ../../var/www/way-to-self; git pull origin main; npm run build; php artisan config:clear; php artisan view:clear; php artisan route:clear; php artisan view:cache; php artisan route:cache;php artisan config:cache"
